In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("c:/users/sakshi yadav/Downloads/Iris_dataset.csv")

In [3]:
df.shape

(150, 6)

In [4]:
df.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [5]:
df = df.drop(columns=["Id"])

In [6]:
df.shape

(150, 5)

In [7]:
df.isnull().sum()

SepalLengthCm    0
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     0
Species          0
dtype: int64

In [8]:
df.duplicated().sum()

np.int64(3)

In [9]:
df = df.drop_duplicates()

In [10]:
df.shape

(147, 5)

In [11]:
flower_list = df['Species'].unique()

In [12]:
dic = dict()

In [13]:
for flower in range(0,len(flower_list)):
    dic.update({flower_list[flower]:flower})

In [14]:
dic

{'Iris-setosa': 0, 'Iris-versicolor': 1, 'Iris-virginica': 2}

In [15]:
def encode(value):
    return dic[value]

In [16]:
df.Species = df.Species.map(encode)

In [17]:
df.head()

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
0            5.1           3.5            1.4           0.2        0
1            4.9           3.0            1.4           0.2        0
2            4.7           3.2            1.3           0.2        0
3            4.6           3.1            1.5           0.2        0
4            5.0           3.6            1.4           0.2        0

In [18]:
df.Species.unique()

array([0, 1, 2])

In [19]:
X = df.drop(columns=['Species'])

In [20]:
y = df.Species

In [21]:
X.head()

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0            5.1           3.5            1.4           0.2
1            4.9           3.0            1.4           0.2
2            4.7           3.2            1.3           0.2
3            4.6           3.1            1.5           0.2
4            5.0           3.6            1.4           0.2

In [22]:
y.head()

0    0
1    0
2    0
3    0
4    0
Name: Species, dtype: int64

In [23]:
X.shape

(147, 4)

In [24]:
y.shape

(147,)

In [25]:
X_copy = X.copy()

In [26]:
for col in X_copy.columns:
    X_copy[col] = (X_copy[col] - X_copy[col].mean()) / X_copy[col].std()

In [27]:
X_copy

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0        -0.912390      1.016496      -1.353111     -1.331149
1        -1.153616     -0.127646      -1.353111     -1.331149
2        -1.394841      0.330011      -1.409958     -1.331149
3        -1.515454      0.101183      -1.296264     -1.331149
4        -1.033003      1.245325      -1.353111     -1.331149
..             ...           ...            ...           ...
145       1.017414     -0.127646       0.807071      1.439759
146       0.534963     -1.271788       0.693377      0.911967
147       0.776188     -0.127646       0.807071      1.043915
148       0.414350      0.787668       0.920765      1.439759
149       0.052512     -0.127646       0.750224      0.780019

[147 rows x 4 columns]

In [28]:
# Standardization in which mean = 0 and std = 1.

In [29]:
X_copy2 = X.copy()

In [30]:
X_copy2

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0              5.1           3.5            1.4           0.2
1              4.9           3.0            1.4           0.2
2              4.7           3.2            1.3           0.2
3              4.6           3.1            1.5           0.2
4              5.0           3.6            1.4           0.2
..             ...           ...            ...           ...
145            6.7           3.0            5.2           2.3
146            6.3           2.5            5.0           1.9
147            6.5           3.0            5.2           2.0
148            6.2           3.4            5.4           2.3
149            5.9           3.0            5.1           1.8

[147 rows x 4 columns]

In [31]:
from sklearn.preprocessing import StandardScaler

In [32]:
scaleStandard = StandardScaler()

In [33]:
transformed_data = scaleStandard.fit_transform(X_copy2)

In [34]:
transformed_data[:5]

array([[-0.91550949,  1.0199714 , -1.35773692, -1.33570001],
       [-1.15755966, -0.12808217, -1.35773692, -1.33570001],
       [-1.39960983,  0.33113926, -1.41477817, -1.33570001],
       [-1.52063491,  0.10152855, -1.30069567, -1.33570001],
       [-1.03653457,  1.24958212, -1.35773692, -1.33570001]])

In [35]:
X_copy2 = pd.DataFrame(transformed_data, columns=X.columns)

In [36]:
X_copy2.head()

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0      -0.915509      1.019971      -1.357737       -1.3357
1      -1.157560     -0.128082      -1.357737       -1.3357
2      -1.399610      0.331139      -1.414778       -1.3357
3      -1.520635      0.101529      -1.300696       -1.3357
4      -1.036535      1.249582      -1.357737       -1.3357

In [37]:
X_copy2.shape

(147, 4)

In [38]:
# Normalization in a specific range of 0 to 1.

In [39]:
'''
Normalization Formula = (x - xmin) / (xmax - xmin)
'''

'\nNormalization Formula = (x - xmin) / (xmax - xmin)\n'

In [40]:
X_copy3 = X.copy()

In [41]:
for col in X_copy3.columns:
    X_copy3[col] = (X_copy3[col] - min(X_copy3[col])) / (max(X_copy3[col]) - min(X_copy3[col]))

In [42]:
X_copy3.head()

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0       0.222222      0.625000       0.067797      0.041667
1       0.166667      0.416667       0.067797      0.041667
2       0.111111      0.500000       0.050847      0.041667
3       0.083333      0.458333       0.084746      0.041667
4       0.194444      0.666667       0.067797      0.041667

In [43]:
X_copy4 = X.copy()

In [44]:
X_copy4.head()

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0            5.1           3.5            1.4           0.2
1            4.9           3.0            1.4           0.2
2            4.7           3.2            1.3           0.2
3            4.6           3.1            1.5           0.2
4            5.0           3.6            1.4           0.2

In [45]:
from sklearn.preprocessing import MinMaxScaler

In [46]:
minmaxscaler = MinMaxScaler(feature_range=(0,1))

In [47]:
transformed_data2 = minmaxscaler.fit_transform(X_copy4)

In [48]:
transformed_data2[:5]

array([[0.22222222, 0.625     , 0.06779661, 0.04166667],
       [0.16666667, 0.41666667, 0.06779661, 0.04166667],
       [0.11111111, 0.5       , 0.05084746, 0.04166667],
       [0.08333333, 0.45833333, 0.08474576, 0.04166667],
       [0.19444444, 0.66666667, 0.06779661, 0.04166667]])

In [49]:
X_copy4 = pd.DataFrame(transformed_data2, columns=X.columns)

In [50]:
X_copy4

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0         0.222222      0.625000       0.067797      0.041667
1         0.166667      0.416667       0.067797      0.041667
2         0.111111      0.500000       0.050847      0.041667
3         0.083333      0.458333       0.084746      0.041667
4         0.194444      0.666667       0.067797      0.041667
..             ...           ...            ...           ...
142       0.666667      0.416667       0.711864      0.916667
143       0.555556      0.208333       0.677966      0.750000
144       0.611111      0.416667       0.711864      0.791667
145       0.527778      0.583333       0.745763      0.916667
146       0.444444      0.416667       0.694915      0.708333

[147 rows x 4 columns]

In [51]:
minmaxscaler2 = MinMaxScaler(feature_range=(1,100))

In [52]:
transformed_data3 = minmaxscaler2.fit_transform(X_copy4)

In [53]:
transformed_data3[:5]

array([[23.        , 62.875     ,  7.71186441,  5.125     ],
       [17.5       , 42.25      ,  7.71186441,  5.125     ],
       [12.        , 50.5       ,  6.03389831,  5.125     ],
       [ 9.25      , 46.375     ,  9.38983051,  5.125     ],
       [20.25      , 67.        ,  7.71186441,  5.125     ]])